### ISSUE TITLE
Can I share my .gitlab-ci.yml?

### ISSUE THREAD

**Issue by nataliawinter** [abhinavs/cookie#4]
Hi, I copied your repository into my gitlab to practice my CI/CD skills.
Your project has some things that I was needed to think about a little more than just deployed a simple Jekyll Website (the template is already done in gitlab).

I was wondering if other people were interested in this. Can I add it to your project? If you want for sure.

Have a good Week

**Comment by abhinavs** [comment]
Yes, definitely. Please add.

Tailwind CSS because of a purging step is not as straightforward, and I have also struggled a lot while adding it to various projects. 

Appreciate your help, thanks a lot.

**Comment by nataliawinter** [comment]
PR #5
