### ISSUE TITLE
webrick

### ISSUE THREAD

**Issue by bingalls** [abhinavs/cookie#6]
This must be the only web server I've ever seen, without a single console/network warning!
Please run
```bash
bundle add webrick
```
I can make a pull request, as you like

**Comment by abhinavs** [comment]
That will be great, please go ahead. Thanks a lot.

**Comment by bingalls** [comment]
https://github.com/abhinavs/cookie/pull/7

**Comment by abhinavs** [comment]
Thanks for the PR - merged it.
