### ISSUE TITLE
build / publish

### ISSUE THREAD

**Issue by bingalls** [abhinavs/cookie#8]
Cookie works fine for development. In production, only the home loads properly!
I tried creating the `bin/publish` script for this.  All built links to local pages fail with 404 errors.
Build fails to put the **.html** suffix on the end of `href` values.

**Comment by bingalls** [comment]
I hacked a solution for this in https://github.com/abhinavs/cookie/pull/9
I also updated gems.
Feel free to implement this in the Jekyll way, instead.

**Comment by abhinavs** [comment]
Will take a look at this - thanks again for this.

**Comment by abhinavs** [comment]
Sorry, I completely missed this thread. If you can resolve the merge issues, will merge the pull request.

**Comment by bingalls** [comment]
Sorry, I've forgotten this code & moved on.
